# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  angular:
    name: Angular Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      # {1} Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {2} Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      # {3} Install dependencies
      - name: Install dependencies
        run: npm ci

      # {4} Clean Distribution Directory
      - name: Clean Distribution Directory
        run: npm run ci:clean

      # {5} Build Application
      - name: Build Application
        run: npm run ci:build

      # {6} Set up SSH Agent with private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # {7} Deploy to server using SSH
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # hostname of the server
          username: ${{ secrets.USERNAME }} # username to login to the server
          port: ${{ secrets.PORT }} # port of the server, often 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/myAngular # navigate to your project directory
            sudo git stash
            sudo git fetch --all
            sudo git pull origin main
            sudo rm -rf /var/www/html/myAngular/dist/my-ang/browser/*
            sudo cp -r dist/my-ang/browser/* /var/www/html/myAngular/dist/my-ang/browser/
            sudo chown -R www-data:www-data /var/www/html/myAngular
            sudo chown -R azureuser:azureuser /var/www/html/myAngular
            sudo chmod -R 755 /var/www/html/myAngular
            
            sudo chown -R www-data:www-data /var/www/html/myAngular/dist
            sudo chown -R azureuser:azureuser /var/www/html/myAngular/dist
            sudo chmod -R 755 /var/www/html/myAngular/dist

            sudo find /var/www/html/myAngular -type d -exec chmod 755 {} \;
            sudo find /var/www/html/myAngular -type f -exec chmod 644 {} \;

            sudo chmod -R 755 /var/www/html/myAngular/dist/my-ang/browser/
            sudo chown -R www-data:www-data /var/www/html/myAngular/dist/my-ang/browser/

            sudo systemctl restart nginx